//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminOrder
    {
        public int idOrder { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> OrderSum { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.DateTime> ArrTime { get; set; }
    }
}
