//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationProg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GasStationDBEntities : DbContext
    {
        public GasStationDBEntities()
            : base("name=GasStationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<FUEL> FUELs { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<AdminOrder> AdminOrders { get; set; }
        public virtual DbSet<AdminOrdersHist> AdminOrdersHists { get; set; }
    
        public virtual ObjectResult<P1_Result> P1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P1_Result>("P1");
        }
    }
}
